### ISSUE TITLE
Problem with enabling a BIE node

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1011]
Normally, if the user enable a descendant BIE node, all the ancestor nodes are automatically enabled. However, this is not the case if there is already a required node in between. Notice in the screenshot below that the Type node is enabled but the Item Identifier Set node is not enabled. The required Identifier node is between the two nodes.

![image](https://user-images.githubusercontent.com/7863166/98450011-e88ce400-2106-11eb-99a3-6ccbdede2d21.png)

**Comment by rekuku** [comment]
Previously, the required node was marked as used, regardless of whether the parent node was used.
This method causes the bug as @kbserm talked about.
So right now, when you just expand node, required node doesn't checked as used.
It is only used when the parent node is enabled.

It is already fixed in #1029, #1020 . So you can check the test.oagiscore.net
![Screen Shot 2020-12-11 at 3 45 51 PM](https://user-images.githubusercontent.com/10194354/101953864-23cc7800-3bc9-11eb-96ff-c99d066f5183.png)
![Screen Shot 2020-12-11 at 3 46 27 PM](https://user-images.githubusercontent.com/10194354/101953866-25963b80-3bc9-11eb-84f2-dd7adecfc865.png)
