### ISSUE TITLE
Getting an error expressing OAS on oagiscore.net

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#1082]
![image](https://user-images.githubusercontent.com/32434235/107244934-32ca7d80-69f4-11eb-963e-788d54c1ccac.png)

Getting an error expressing OAS.  This is for ShippedItemInstance.  Likely related to metaheader.

**Comment by dubnemo** [comment]
disabling metaheader works

![image](https://user-images.githubusercontent.com/32434235/107265104-7c719300-6a09-11eb-8a84-319cae8cb8e1.png)

**Comment by rekuku** [comment]
Yes, @dubnemo this is a bug caused by different branches of BIE and MetaHeader/PaginationResponse.
Now the dialog to display only MetaHeader/PaginationResponse from the same Branch as BIE.
Please test it. @asdimitriadis 

<img width="1189" alt="Screen Shot 2021-02-08 at 5 01 18 PM" src="https://user-images.githubusercontent.com/10194354/107287124-81e1d400-6a2f-11eb-800f-aea8ea73ba17.png">

**Comment by dubnemo** [comment]
I verified this in test.oagiscore.net, and this now works for both JSON Schema and OpenAPI Spec.
