### ISSUE TITLE
Copy from exist function must be idempotent

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1109]
The issue is that we can copy the same modules multiple times which leads to duplicate modules.

To reproduce the issue:
1. Create a ne Module Set
2. Open it to edit it.
3. Click "add" button
4. Go to option "Copy from exist"
5. Select a directory (e.g., model) and click Copy button
6. Repeat the steps 4 and 5 again

At this point there will be duplicate modules; i.e., the same modules and directories multiple times.

Copy function must be idempotent, i.e., the developer can copy from multiple module sets or the same set multiple times and only modules not already exist in the current module set shall be added.

**Comment by rekuku** [comment]
It was fixed with #1110.
If you do the same copy several times on the same point, you will have different suffixes.

**Comment by kbserm** [comment]
@rekuku In Windows, duplicate folders are merged, and duplicate files are either overridden or duplicate with the suffixed depending on user's input. Is it the same in Mac? Maybe that is more of the expected behavior. But I understand if that is complicated to implement and we can live with what you have done, i.e., users would have to merge folders manually.

**Comment by asdimitriadis** [comment]
It works good now. 
The copy function is idempotent. 
No duplicate Modules Directories or Files are created if you select to copy same Directory or File.
