### ISSUE TITLE
Improve the downloadable Uplift Report format and content

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#1140]
Recommendations to the Report to make it more usable.

1. Filename should be UpliftReport-BIEName-Guid.csv
2. Need to include Source Context Definition in Quotes.  Rationale: there are many id/typeCode or extensions that use generic properties that get mapped to more refined qualified properties in the newer target release, and these are most often populate in the Source context definition. 
3. Column Label: Source $ReleaseId Path, Source Context Definition, Target $ReleaseId Path, Type (ASCCP, BCCP)
3. Target Release Path column should display the NEW properties added in the newer release not available in the Source Release.  Rationale: show the available, more qualified or missing components that are now available; with goals to provide simpler and less generic BIEs and reduce the number of arrays for generic structures.

**Comment by kbserm** [comment]
(3) -> So many things are in the type codes. Mapping to the new release depends on the values in the type code, typically documented in the context definition.
(4) -> provide delta between the two releases. Maybe just flag the fields/components that are differences between the two releases.

Maybe option for more compact report to exclude the auto-mapped ones as an option. Sometimes type code usage cause auto-map to be incorrect. For example, shipment type code was used with the ID in the previous release that should be switch to a new qualified Shipment ID field.

**Comment by kbserm** [comment]
@dubnemo the report already includes the fields mapped by the system. Just uncheck the check box on the top.
![image](https://user-images.githubusercontent.com/7863166/119400338-0b987300-bca8-11eb-9b0c-2846961c948e.png)

**Comment by kbserm** [comment]
@dubnemo 

#1 to #3 you proposed above are straightforward. 

We can should be able to provide #4 you proposed above. Right now since we cannot handle DT management yet, new properties will either be BCC or ASCC. Now from the BIE perspective, if a new ASSC is added somewhere, it would mean that the entire structure/hierarchy of the ACC used by that ASCC constitutes new properties. I.e., should we report only that ACC as a new property or the entire structure of the ACC as new properties?

**Comment by dubnemo** [comment]
@kbserm 
Feature 4: I was suggesting only the new property.   This will be a  sufficient checklist for detailed review.  I will print it off, and then work through the checklist details in the BIE edit mode not in the Uplift mode.   The Source Context Definition will hightlight the important clues for the BIE edit.

**Comment by kbserm** [comment]
@dubnemo The problem is the new property could be deep down in the hierarchy of the target release BIE , so Feature needs a good amount of effort. We will defer feature 4 to another release in a separate issue. In this release, we will add the Context definition and update the column names as you suggested. The new issue is #1186.

**Comment by dubnemo** [comment]
@kbserm "In this release" do you mean the next release Score 2.2?

**Comment by kbserm** [comment]
@dubnemo yes.

**Comment by rekuku** [comment]
![Screen Shot 2021-09-02 at 2 56 58 PM](https://user-images.githubusercontent.com/10194354/131901231-8d9f97fc-e326-4e58-bda9-f95fe6ead547.png)
The type and Context definition was added to the download and report page.
Please test this. @asdimitriadis

**Comment by asdimitriadis** [comment]
It works well. Type and context definition have been added. Also the release is added in the source and path column
