### ISSUE TITLE
Change BIE pages to show DEN instead of just property term

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#1188]
This is motivated by Extension which uses the same property term. Lockheed reuses Extension and they cannot differentiate different Extension BIEs.

@joshklm Please add comments if additional info is needed.

**Comment by joshklm** [comment]
This issue is related to #1181 

@kbserm In the BIE page, property terms are used for ASCCP and BCCP, for others, I think, Object Class Terms are used for display even though the column header says 'property term'. It gets even more confusing in the BIE meta info pane b/c it doesn't  have any fields to show DEN, property term or object class term values. 

Showing DEN in BIE page seems to be a major shift in user experience. So far in SCORE, BIE profiling activities are separated from Core Component activities - where users working on BIE profiling are somewhat purposefully shielded from understanding DEN, Property Term, Object Class Term and all different Core Component types of CC, ASCCP, ASCC, BCC and BCCP. Start showing DEN in BIE page would mean that those users now need to understand the Core Component structures (e.g. xxx.Details, xxx Base.Details). And that would also require showing additional Core Component info in the BIE meta info pane as well.

**Comment by hakjuoh** [comment]
@kbserm It replaced with 'DEN'. Originally, we decided to use 'Property Term', because most ASCCPs' DEN in OAGIS have a recurrent sequence with the same term like 'Move Inventory. Move Inventory'. At this point, I'm not sure how this change will affect to user experiences.

<img width="492" alt="Screen Shot 2022-07-12 at 3 58 53 PM" src="https://user-images.githubusercontent.com/16102116/178583216-7485173b-c449-47f5-81d2-9655f3a87239.png">

**Comment by kbserm** [comment]
@hakjuoh this look fine, although I can't see it on the current test instance.
