### ISSUE TITLE
Definition and Definition Source of a SC are not propagated to 2nd level DTs

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1241]
To reproduce the issue:
1. Create DT1 and add a new SC1
2. Set the Definition and Definition source of SC1
3. Create DT2 based on DT1
4. Create DT3 based on DT2

At this point the Definition and Definition Source of SC1 in DT3 are empty. They should be the same as the ones in SC1 of DT1

**Comment by hakjuoh** [comment]
@asdimitriadis It changes to properly propagating both `definition` and `definitionSource` for both DT and DT_SC.

**Comment by asdimitriadis** [comment]
@hakju the SC detail are propagated correctly now. 

Could you also please check the following details of the DT (i.e., the root node):
a. Qualifier
b. Default Value Domain 
c. Definition
d. Definition Source
e. Content Component Definition

Changes to all the above are not propagated to the derived DTs.

**Comment by hakjuoh** [comment]
@asdimitriadis Would you give me any method to reproduce the problem that not properly propagating properties from the base? Because I put some random strings on all properties like below, and it worked.

<img width="591" alt="Screen Shot 2022-01-31 at 9 55 55 AM" src="https://user-images.githubusercontent.com/16102116/151816223-f13bfd01-c562-4497-a303-a8b66136d933.png">

**Comment by hakjuoh** [comment]
@asdimitriadis Now 'Default Value Domain', 'Definition', 'Definition Source', and 'Content Component Definition' changes on the base DT are propagating to derived DTs.

**Comment by asdimitriadis** [comment]
It works well.
