### ISSUE TITLE
Exclude SC in BIE disables SCs nodes 

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1269]
The issue is that when the "Exclude SC" is disabled and the enabled again, some SC nodes are disabled. 
This issue happens only if same SC nodes are enabled. 

One example to reproduce the issue is:
1. Create the "Transfer Order Reference" BIE
2. Enable all SCs under the "Identifier", "Revision Identifier" and "Variation Identifier" nodes. 
3. Update the BIE
4. Uncheck the "Exclude SC"
5. Check the "Exclude SC"

At this point all SC nodes under the  "Identifier", and "Revision Identifier" are disabled (i.e., unused). The SC nodes under the "Variation Identifier" are enabled (i.e., Used) though. 

Please see attached a screenshot. 
![exclude scissue](https://user-images.githubusercontent.com/37205288/160184234-fa56d137-0771-4713-8c98-f15426253e8c.png)

**Comment by hakjuoh** [comment]
@asdimitriadis The actual problem was not in a 'Exclude SCs' feature. You can see unmarked BBIE_SCs even if you don't click 'Exclude SCs' button. Actually, the problem was that it can't show 'Used' markings if there are duplicate 'used' components in the tree. In this case, all SCs are duplicated in multiple BBIEPs. Now it fixes using a `hashPath` property.

<img width="423" alt="Screen Shot 2022-03-28 at 9 56 06 AM" src="https://user-images.githubusercontent.com/16102116/160413765-395a3622-6163-4501-8de3-a729c4c74daf.png">

**Comment by asdimitriadis** [comment]
It works well now.
