### ISSUE TITLE
Error when exporting Module Set Release

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#1279]
The issue is that in some cases (like the scenario below) the export function of the Module Set Release returns a gateway error.

To reproduce the issue:
1. Create a Module Set Release by choosing OAGIS 10.8 Canonical XML Schema and 10.8 (no copy CC assignments should be chosen). 
2. Make some CC assignments and leave some CCs unassigned (e.g., assign only the "Absence Type Code. Code" to a module). 
3. Reopen the Module Set Release and click "Export"

At this point, a gateway error is returned.

**Comment by hakjuoh** [comment]
@asdimitriadis This happens because the required reference 'clm63055D16B_AgencyIdentification' is not assigned. I changed the behavior to show the following error message:
<img width="541" alt="Screen Shot 2022-04-12 at 2 03 59 PM" src="https://user-images.githubusercontent.com/16102116/163025662-cbced23a-61ba-4008-a34c-9ede394c2313.png">

**Comment by asdimitriadis** [comment]
It works well.
