### ISSUE TITLE
Update Resource Path in OAS expression to include Business Context and Version

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#1308]
RESTful Web API Design V2 document suggests URI conventions, including path-domain/version/resource (~ page 60).

We can accelerate this OAS specification by using this convention in Score OAS expression capability:
`<business-context>/<version/<bie-name>`.

We only use `/<bie-name>` today.

Note that RESTful Web API Design V2 also specifies the use of hyphen when the domain (business context) instead of spaces (not lowercase, lowerCamelCase, UpperCamelCase).

**Comment by dubnemo** [comment]
@kbserm we already have a full set of wireframes and a data model that
describes this, as well as a RESTful Web API Design document.  This request
is only one small step forward towards full OAS authoring.

**Comment by hakjuoh** [comment]
@dubnemo @kbserm 

<img width="904" alt="Screen Shot 2022-07-22 at 9 07 00 AM" src="https://user-images.githubusercontent.com/16102116/180445492-3161744a-3544-4caf-b2be-df1966736116.png">

`/s-series/v1_0/moveProduct` for the first case, following the issue #1267 that replaces the dot character "." in the version property with the underscore character "_". And
`/test/moveProduct` for the second case that doesn't have a version

However, RESTful Web API Design v2 document stated
> In order to avoid confusion (e.g. due to the possibility of being obscured), the underscore character “_” should not be used in URIs.
> **R86** For the URI path, the underscore character "__" SHOULD not be used in URIs

Should we use the hyphen '-' instead of the underscore '_' for the dot character replacement?
Please let me know your idea about it.

**Comment by dubnemo** [comment]
Periods are permitted in a URI.
No translation required.

**Comment by hakjuoh** [comment]
@dubnemo @kbserm R85 - R87 rules are applied to path names.
> [R85] For URI path segments, consisting of more than a single word, a hyphen character “-“ SHOULD be used to separate the words.

```java
if (isVersion(str))
   str = str.replaceAll("\s", "")
else
   str = str.replaceAll("\s", "-")
```

> [R86] For the URI path, the underscore character “_”SHOULD not be used in URIs.

```java
str = str.replaceAll("[^A-Za-z0-9]", "-")
```

> [R87] For the URI path, lower case letters SHOULD be used.

```java
str = str.toLowerCase()
```

| Property Term | Business Term | Version | Result |
| --------------- | --------------- | --------- | ------ |
| Move Product | S-Series | V1.0 | /s-series/v1-0/move-product |

**Comment by dubnemo** [comment]
The version is unlikely to have a minor notation, only major.

@sfohn
