### ISSUE TITLE
Only one Business Term can be assigned for the top-level ASBIEP

### ISSUE THREAD

**Issue by elenajelisic** [OAGi/Score#1325]
There is no 'Assign New Business Term' button for the top-level ASBIEP.

![image](https://user-images.githubusercontent.com/103444540/190467706-50d81cb5-ecf6-4dba-8c8b-20b74a365919.png)

**Comment by DimitrijeM** [comment]
Thank you for noticing that. It should be like that by design. We agreed that in the first version of business term implementation, we will support multiple business term assignments only for the properties (ASBIEP and BBIEP). For now, top-level BIE can have only one business term. 
It can be discussed with the working group should we introduce multiple business terms for top-level BIE in the next iteration.
