### ISSUE TITLE
Business term and code list management should be limited to Admins for multi-tenant.

### ISSUE THREAD

**Issue by jim-wilson-kt** [OAGi/Score#1364]
![image](https://user-images.githubusercontent.com/2702530/209052306-319df3a2-d4d7-4017-9b71-1e8246a4c121.png)

**Comment by hakjuoh** [comment]
Business term assignments in BIEs[#602] will be a part of BIE management functionalities for any user in Score 2.5. @kbserm I'll remove it if we plan to move that issue to the next Score milestone like 2.6.

**Comment by kbserm** [comment]
@jim-wilson-kt I won't talk about business term right now, b/c it is not supposed to be in 2.5 or multi-tenant yet. So it should be removed for every case right now.

I take that the decision to limit Code List management to admin is more or less for the reason of simplification or licensing. Let me get into more detail here. Please note that there is also a View/Edit Code List menu item also under the Core Component menu and it open the same page as the menu item under BIE.

Generally, code list management is available to both developers and end users. 1) Developer manages code lists for standard releases. 2) End users will want to view those standard code lists in order to use them in BIEs. 3) End users are allowed to add/create new (user specific) code lists to/in specific release branches to use in BIEs in that release. IMO, it is perfectly fine to restrict #1 in multi-tenant; it is quite a severe limitation for #2; it is relatively okay to limit #3.

Enabling #3 is rather complicated b/c there is no business context associated. (But that led me to think why we have to use business context to filter BIE at this point. Your original thought was using BC so that there is no need to add new table/columns about tenant, but we now have tenant in Score database, so at this point using BC seems redundant). 

I see that you have hidden all the CC related menus under multi-tenant. However, the end user can still inspect CCs when creating BIE - during searching for CCs. So one way to enable #2 is to display the code list as a link in the BCC and BCCP detail pane and/or display code lists as links in the domain value restriction in the BIE detail pane (not sure if this is possible as it is a drop down list). This can be a future enhancement if you are so inclined.

**Comment by hakjuoh** [comment]
@jim-wilson-kt I added 'Application Settings' menu that allows users to modify the configurations.

<img width="1423" alt="Screen Shot 2023-01-11 at 11 04 51 AM" src="https://user-images.githubusercontent.com/16102116/211855931-2d769411-d34a-4b49-8f72-fc4f98845eb5.png">

To see the menu, click 'Settings' menu, and click 'Application settings' button. Only 'Admin' user can access this function.

**Comment by jim-wilson-kt** [comment]
@kbserm I am closing this issue but note for the first time your 2022-12-22 comment. (Sorry, I don't pay attention to GitHub notifications, but clearly should.) I would like to revisit this topic in the future. Thank you for your comment. Regarding the issue overall, in testing on https://tenant.oagiscore.net, it appears to behave as requested.
