### ISSUE TITLE
Removing a Reused BIE at Lower Level removes a higher level reference to a different reused 

### ISSUE THREAD

**Issue by smorgan19** [OAGi/Score#1486]
When an attribute is present a multiple levels, example, BOM->BomItemData, and BOM->BomOption->BomItemData, If two reused bies that are different at each level are present and you attempt to remove the lower level reused bie, it removes to higher level bie instead.  So if we attempted to remove BOMOption's BOMItemData reused BIE, it instead removed the BOM's BOMItemData and BOMOption's BOMItemData is still attached.

**Comment by hakjuoh** [comment]
@bingqi2045 Please review [this PR](https://github.com/OAGi/Score/pull/1490).

**Comment by bingqi2045** [comment]
just tested with the same example BOM->BomItemData, and BOM->BomOption->BomItemData.  The issue is fixed. 

Before removing the lower-level BIE,

<img width="596" alt="Screenshot 2023-05-09 at 5 26 59 PM" src="https://github.com/OAGi/Score/assets/117864643/171e842d-3c83-4173-b707-ff203bacde04">

After removing the lower-level BIE,


<img width="510" alt="Screenshot 2023-05-09 at 5 27 25 PM" src="https://github.com/OAGi/Score/assets/117864643/d83d3b76-c4e1-444f-b434-5fcb66ba3700">
