### ISSUE TITLE
Update Score logo to connectCenter logo for tenant.oagiscore.net

### ISSUE THREAD

**Issue by michaelfigura** [OAGi/Score#1535]
@jim-wilson-kt @hakjuoh this may be of interest to you.

![connectCenter Logo Landscape](https://github.com/OAGi/Score/assets/36652082/266db0eb-8bb4-4b59-a746-06a3e7b88ece)

**Comment by michaelfigura** [comment]
I think we should also apply the new logo to demo.oagiscore.net. Perhaps all of them, except the on-prem docker images?

**Comment by hakjuoh** [comment]
@michaelfigura Here's a new look of the menu bar.
<img width="1148" alt="Screenshot 2023-08-17 at 3 33 58 PM" src="https://github.com/OAGi/Score/assets/16102116/9c090d44-4cb0-4ece-b89b-016dbf1714c4">

Do we need to the logo from the on-prem instances? In order to deploy this new logo, I should build a new docker image.
