### ISSUE TITLE
Cannot change the BDT of Value BCCP

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#1536]
Goal is to change this to Open Field_ Value. Type, which has Format and Type Code attributes.

![image](https://github.com/OAGi/Score/assets/32434235/44f5b1fa-2de2-4959-9498-6d4f54d8f539)

**Comment by dubnemo** [comment]
I believe we had this capability for BCCPs in the past.

**Comment by dubnemo** [comment]
@hakjuoh unclear what you mean by Rev. 1.  Are you confirming we had it, and it is no longer there?

**Comment by bingqi2045** [comment]
@dubnemo  We currently don't allow the revised BCCP to change BDT. I just tried on my local,  i cannot change the BDT either. 

@kbserm  Will we remove the restriction for revised BCCP?

**Comment by kbserm** [comment]
This appear to me as an incorrect implementation. Test Assertion [#10.21.2](https://github.com/OAGi/Score/blob/master/docs/test_cases/TestSuite10.md#test-assertion-10212), which is about `Editing a revision of a developer BCCP` states `The associated BDT can be changed.`  

The [user guide](https://test.oagiscore.net/docs/ScoreUserGuide.html#revise-a-bccp) may make it sounds like it should not be available. So user guide should also be updated accordingly after this issue is fixed.

**Comment by kbserm** [comment]
Also test script for 10.21.2 should be checked to why it does not catch this missing function.

**Comment by bingqi2045** [comment]
@kbserm  the test script for 10.21.2 is fixed and the user guide is updated to reflect that the associated BDT can be changed for a revised BCCP.
