### ISSUE TITLE
Validation 500 error when running module set release validation

### ISSUE THREAD

**Issue by michaelfigura** [OAGi/Score#1551]
![image](https://github.com/OAGi/Score/assets/36652082/9aa12f95-ffa0-4372-9453-3568be57875d)

**Comment by kbserm** [comment]
@hakjuoh Is my understanding right that the user got 500 error b/c the XML schemas were failed to be generated? Not sure if that is the only possible cause, but if so we should convey that specific message.

**Comment by kbserm** [comment]
@michaelfigura Keep in mind that the cause of error is usually because you assign components to the module that cause circular XML schema import/include. Please consider whether the module assignment could cause this situation, If you haven't already done so. 

@hakjuoh Is there away to report this problem from your XML Schema generation algorithm as I think it is quite difficult for a human to sort through this.

**Comment by hakjuoh** [comment]
@kbserm @michaelfigura `Duration. Open Duration Measure_ Duration` BCCP revised in Working release, but left it in WIP state. Although the BCCP should point to the previous DT, it pointed to the revised DT in `Working` branch. That's a bug. I fixed the DB record manually now.

**Comment by kbserm** [comment]
@hakjuoh You also fixed the root cause?

**Comment by hakjuoh** [comment]
> @hakjuoh You also fixed the root cause?

This is a temporary fix. I would like to revise all functions in DT management and introduce XBT management to fix the root cause of the problem. The main issue to address is the separation of BDTs from CDTs along with primitive types.
