### ISSUE TITLE
OpenAPI Document list  not displaying properly in Chromium - previously worked fine.

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#1588]
Somehow this list is not displaying properly in Chromium on Ubuntu.

![image](https://github.com/OAGi/Score/assets/32434235/955db15f-99fa-4f84-8563-7cc7c2dce116)

But works fine in Chrome on Windows:
![image](https://github.com/OAGi/Score/assets/32434235/c0da0e9e-808c-4468-a6c0-f53b3c158dc1)

**Comment by dubnemo** [comment]
And it is seems be OK in Chromium on my Raspberry Pi4B.

![2024-01-06-085309_1920x1080_scrot](https://github.com/OAGi/Score/assets/32434235/915844af-c704-4a19-b56f-b8c386874d99)

**Comment by dubnemo** [comment]
This no longer works in Edge, which is based on Chromium.
![image](https://github.com/OAGi/Score/assets/32434235/007aa585-300a-4b3d-85c5-3a0c8cc450f2)

**Comment by hakjuoh** [comment]
@dubnemo It seems that the problem is not due to different browsers, but due to different display resolutions. Currently, the width of all columns except the Description column is fixed. The values of column widths are too large, so the Description item is not displayed properly even if the screen is slightly changed.
@elena-jelisic It can be solved by adjusting the width of columns or making the columns variable, and applying text-overflow: ellipsis to the description.

**Comment by hakjuoh** [comment]
@elena-jelisic Applied the mat-multi-sort and changed column widths (See [commit](https://github.com/OAGi/Score/commit/6762cb53b8fbe34b4dac608f12bdf7304a407215))
