### ISSUE TITLE
OpenAPI document - insert into oas_resource_tag when updating BIE

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#1589]
Clicked on the BIE from the OpenAPI document view that contains the list of BIEs association to the OpenAPI document.
After editing the BIE's version and remark, received this error message:

jOOQ; SQL [insert into `oagi`.`oas_resource_tag` (`created_by`, `last_updated_by`, `creation_timestamp`, `last_update_timestamp`, `oas_tag_id`, `oas_operation_id`) values (?, ?, ?, ?, ?, ?) returning `oas_tag_id`]; (conn=3506) Cannot add or update a child row: a foreign key constraint fails (`oagi`.`oas_resource_tag`, CONSTRAINT `oas_resource_tag_oas_operation_id_fk` FOREIGN KEY (`oas_operation_id`) REFERENCES `oas_operation` (`oas_operation_id`))

![image](https://github.com/OAGi/Score/assets/32434235/27a2175d-0a56-41ca-8eef-c3c749197866)

Removed the BIE from the OpenAPI document
Edited the BIE without its association to the OpenAPI document, updated fine.
Re-added to OpenAPI document with no problem.

**Comment by hakjuoh** [comment]
@elena-jelisic Bingqi and I tried to implement a feature for Issue #1519 and removed it for the 3.2.1 version release. However, some parts remained, causing this issue. The goal of the issue was to apply the changes to the OpenAPI document on the BIE page. To achieve this, there was additional information passed to the BieForOasDoc object. Removing this part should resolve the issue. Let's address Issue #1519 and make improvements separately after fixing this.

**Comment by hakjuoh** [comment]
@elena-jelisic Removed the BieForOasDoc object as mentioned earlier (See [commit](https://github.com/OAGi/Score/commit/b1f9d48867e02872fcd666d3d7c86bd29b9b6fca))
