### ISSUE TITLE
AVSC schemas are generating with invalid integer field

### ISSUE THREAD

**Issue by smorgan19** [OAGi/Score#1602]
Integers are represent as int in avro, but when expressed integer is spelled out.  For a valid schema the value should be int.
![image](https://github.com/OAGi/Score/assets/56837736/5f0cf2eb-ce69-495d-acdf-c38825ea89d8)

![image](https://github.com/OAGi/Score/assets/56837736/3685f39a-28f6-4f9f-b1a4-db602f6f616e)
https://avro.apache.org/docs/1.11.1/specification/

**Comment by hakjuoh** [comment]
@smorgan19 Thanks for reporting this issue. We've used `xbt`.`avro_map` columns to express data types in the AVRO schema format, and I found out that there are three numeric types mapped to 'integer', not 'int'.
```sql
SELECT `xbt_id`, `name`, `avro_map` FROM `xbt` WHERE `avro_map` LIKE '%integer%';
```
| xbt_id | name | avro_map |
| ----- | ----- | --------- |
| 21 | integer | {"type":"integer"} |
| 22 | non negative integer | {"type":"integer"} |
| 23 | positive integer | {"type":"integer"} |

This can be fixed by executing the following update query:
```sql
UPDATE `xbt` SET `avro_map` = '{"type":"int"}' WHERE `xbt_id` IN (SELECT `xbt_id` FROM `xbt` WHERE `avro_map` LIKE '%integer%');
```

If this is urgent, you can execute that update query directly.
