### ISSUE TITLE
test

### ISSUE THREAD

**Issue by jaehun-lee** [OAGi/Score#27]
test

**Comment by hakjuoh** [comment]
> **Format preview** ([#1533](https://github.com/OAGi/Score/issues/1533)) — AGENCY_ID_LIST · New · Draft→Candidate. _Posted from a local test instance; links point to localhost._

### New BCCP "NAICS Code. Open_ Code" — Revision 1

A new component addressing this issue has reached **Candidate**.

- Property Term: NAICS Code
- Data Type: Open_ Code. Type
- Representation Term: Code
- Namespace: http://www.openapplications.org/oagis/10
- Definition: A NAICS Code, or North American Industry Classification System Code, is a standardized system used to classify businesses based on their primary activities. This NAICS Code classification helps in the collection, analysis, and publication of statistical data related to the U.S. economy. Accurate NAICS Information is crucial for businesses because they affect eligibility for government contracts, loans, and tax benefits, and they facilitate better communication with government agencies. A six-digit NAICS Code classifies businesses by industry group in a hierarchical structure, where each digit represents a specific level of detail about the business's activities. This system helps to organize and analyze economic data across the U.S., Canada, and Mexico. There is no central government agency with the role of assigning, monitoring, or approving NAICS codes for establishments. NAICS Codes are self-assigned based on the establishment’s primary activity (the activity that generates the most revenue for the establishment). Individual establishments are assigned NAICS codes by various agencies for various purposes using a variety of methods. The U.S. Census Bureau has no formal role as an arbitrator of NAICS classification. The U.S. Census Bureau assigns one NAICS code to each establishment based on its primary activity (the activity that generates the most revenue for the establishment) to collect, tabulate, analyze, and disseminate statistical data describing the economy of the United States. Generally, the U.S. Census Bureau’s NAICS classification codes are derived from information that the business establishment provided on administrative, survey, or census reports. (e.g. when a company applies for an Employer Identification Number (EIN), information about the type of activity in which that business is engaged is requested in order to assign a NAICS code).

[View this component in connectCenter](http://localhost:4200/core_component/bccp/179317)

**Comment by hakjuoh** [comment]
> **Format preview** ([#1533](https://github.com/OAGi/Score/issues/1533)) — DT · Revised · Draft→Candidate. _Posted from a local test instance; links point to localhost._

### DT "Duration" — Revision 2 reached Candidate

Changes from Revision 1:

<details><summary>Added (1)</summary>

- Supplementary Component "Unit. Code"
  - Cardinality: 0..1
  - Definition: Maintains the unit of measure associated with the duration. i.e. days, minutes, etc.

</details>

[View this component in connectCenter](http://localhost:4200/data_type/1166)

**Comment by hakjuoh** [comment]
### ASCCP "Move Product Forecast. Move Product Forecast" (rev. 2) was reverted to WIP

The following changes, previously a **Candidate** for this issue, moved back to **WIP** and may be reworked:

- Definition: (none) → "The advance projected forecast of the future movement of one or more products."

[View this component in connectCenter](http://localhost:4200/core_component/asccp/5533)

**Comment by hakjuoh** [comment]
### Code List "Payment Means Code" (rev. 1) was reverted to WIP

The following changes, previously a **Candidate** for this issue, moved back to **WIP** and may be reworked:

- Name: "Code List" → "Payment Means Code"
- List ID: "fec4e959085748e49415db881a992689" → "4461"
- Agency ID: "OAGi (Open Applications Group, Incorporated)" → "6 (UN/ECE (United Nations - Economic Commission for Europe))"
- Version: "1" → "2002A"
- Namespace: (none) → "http://www.openapplications.org/oagis/10"
- Definition: (none) → "4461 - Payment means code https://unece.org/fileadmin/DAM/trade/untdid/d16b/tred/tred4461.htm"
- Definition Source: (none) → "UN/EDIFACT D.16B"

<details><summary>Added (27)</summary>

- Value "1"
  - Meaning: Instrument not defined
  - Definition: Not defined legally enforceable agreement between two or more parties (expressing a contractual r...
  - Definition Source: D.16B
- Value "2"
  - Meaning: Automated clearing house credit
  - Definition: A credit transaction made through the automated clearing house system.
  - Definition Source: D.16B
- Value "3"
  - Meaning: Automated clearing house debit
  - Definition: A debit transaction made through the automated clearing house system.
  - Definition Source: D.16B
- Value "4"
  - Meaning: ACH demand debit reversal
  - Definition: A request to reverse an ACH debit transaction to a demand deposit account.
  - Definition Source: D.16B
- Value "5"
  - Meaning: ACH demand credit reversal
  - Definition: A request to reverse a credit transaction to a demand deposit account.
  - Definition Source: D.16B
- Value "6"
  - Meaning: ACH demand credit
  - Definition: A credit transaction made through the ACH system to a demand deposit account.
  - Definition Source: D.16B
- Value "7"
  - Meaning: ACH demand debit
  - Definition: A debit transaction made through the ACH system to a demand deposit account.
  - Definition Source: D.16B
- Value "8"
  - Meaning: Hold
  - Definition: Indicates that the bank should hold the payment for collection by the beneficiary or other instru...
  - Definition Source: D.16B
- Value "9"
  - Meaning: National or regional clearing
  - Definition: Indicates that the payment should be made using the national or regional clearing.
  - Definition Source: D.16B
- Value "10"
  - Meaning: In cash
  - Definition: Payment by currency (including bills and coins) in circulation, including checking account deposits.
  - Definition Source: D.16B
- Value "11"
  - Meaning: ACH savings credit reversal
  - Definition: A request to reverse an ACH credit transaction to a savings account.
  - Definition Source: D.16B
- Value "12"
  - Meaning: ACH savings debit reversal
  - Definition: A request to reverse an ACH debit transaction to a savings account.
  - Definition Source: D.16B
- Value "13"
  - Meaning: ACH savings credit
  - Definition: A credit transaction made through the ACH system to a savings account.
  - Definition Source: D.16B
- Value "14"
  - Meaning: ACH savings debit
  - Definition: A debit transaction made through the ACH system to a savings account.
  - Definition Source: D.16B
- Value "15"
  - Meaning: Bookentry credit
  - Definition: A credit entry between two accounts at the same bank branch. Synonym: house credit.
  - Definition Source: D.16B
- Value "16"
  - Meaning: Bookentry debit
  - Definition: A debit entry between two accounts at the same bank branch. Synonym: house debit.
  - Definition Source: D.16B
- Value "17"
  - Meaning: ACH demand cash concentration/disbursement (CCD) credit
  - Definition: A credit transaction made through the ACH system to a demand deposit account using the CCD paymen...
  - Definition Source: D.16B
- Value "18"
  - Meaning: ACH demand cash concentration/disbursement (CCD) debit
  - Definition: A debit transaction made through the ACH system to a demand deposit account using the CCD payment...
  - Definition Source: D.16B
- Value "19"
  - Meaning: ACH demand corporate trade payment (CTP) credit
  - Definition: A credit transaction made through the ACH system to a demand deposit account using the CTP paymen...
  - Definition Source: D.16B
- Value "20"
  - Meaning: Cheque
  - Definition: Payment by a pre-printed form on which instructions are given to an account holder (a bank or bui...
  - Definition Source: D.16B
- Value "21"
  - Meaning: Banker's draft
  - Definition: Issue of a banker's draft in payment of the funds.
  - Definition Source: D.16B
- Value "22"
  - Meaning: Certified banker's draft
  - Definition: Cheque drawn by a bank on itself or its agent. A person who owes money to another buys the draft...
  - Definition Source: D.16B
- Value "23"
  - Meaning: Bank cheque (issued by a banking or similar establishment)
  - Definition: Payment by a pre-printed form, which has been completed by a financial institution, on which inst...
  - Definition Source: D.16B
- Value "24"
  - Meaning: Bill of exchange awaiting acceptance
  - Definition: Bill drawn by the creditor on the debtor but not yet accepted by the debtor.
  - Definition Source: D.16B
- Value "25"
  - Meaning: Certified cheque
  - Definition: Payment by a pre-printed form stamped with the paying bank's certification on which instructions...
  - Definition Source: D.16B
- Value "26"
  - Meaning: Local cheque
  - Definition: Indicates that the cheque is given local to the recipient.
  - Definition Source: D.16B
- Value "27"
  - Meaning: ACH demand corporate trade payment (CTP) debit
  - Definition: A debit transaction made through the ACH system to a demand deposit account using the CTP payment...
  - Definition Source: D.16B

</details>

[View this component in connectCenter](http://localhost:4200/code_list/440)
