### ISSUE TITLE
The Abstract checkbox should be editable on the ACC create/edit page

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#507]
Unless we say that when the Base component type is selected, the Abstract is automatically checked.

**Comment by rekuku** [comment]
@kbserm I put in "(Abstract)" to "Base" in ComponentType, and it check automatically Abstract checkbox.
But It has NOT makes disabled Abstract checkbox, because there's some data that "ComponentType = Base and Abstract = False" exist.
If we makes Abstract checkbox to disabled then these data can not be edited as Abstract = true. 

@asdimitriadis Please test this. Thank you.

**Comment by asdimitriadis** [comment]
This is tested and it works with the following logic:
1. If the Component Type is "Base (Abstract)", the Abstract checkbox is automatically checked and disabled (it cannot be unchecked).
2. Abstract can only be true when the Component Type is "Base (Abstract)" or Semantics. In the latter case he Abstract checkbox can be true or false (it is enabled).

Also, we discussed (on 8/31/2020 meeting) about the situation of the "Sampling Plan Document Reference Base. Details" that has component type "Base (Abstract)" but the abstract checkbox is unchecked.

Therefore, I am closing this issue.
