### ISSUE TITLE
Add a reset button on the BIE detail pane

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#568]
The reset button would put reset all the fields to the initialized values.

**Comment by rekuku** [comment]
![Screen Shot 2021-06-15 at 11 58 56 AM](https://user-images.githubusercontent.com/10194354/122085934-353d4980-cdd1-11eb-8854-17cabcd9e01c.png)

I was two buttons,
The reset button on the top right is a global reset button that clear all details and used,
The second button on the top right of each detail is resetting only the current detail.

**Comment by kbserm** [comment]
Does global have confirmation dialog?

**Comment by asdimitriadis** [comment]
@rekuku 
When we click the button the node becomes unused always. 
The issue is that the reset node detail button does not consider the Used checkbox.

The expected behavior is that if a node was used it should be remain used if we click that reset node detail button. 
On the other hand if that node was unused and we click the reset node detail button the node should become unused. 

Also, according to Serm's comment we need a confirmation box when we click the global reset button.

**Comment by rekuku** [comment]
![Screen Shot 2021-07-14 at 3 06 03 PM](https://user-images.githubusercontent.com/10194354/125678496-e871fcf4-676a-4976-8bef-9c8f1acc040c.png)

A confirm dialog added to global reset button.

Now, Detail's icon-button reset the "Used" information as well. @asdimitriadis

**Comment by asdimitriadis** [comment]
It works fine.

**Comment by kbserm** [comment]
@asdimitriadis Could you double check again.

I tried the global reuse and the used box still remains used. But I would propose to remove the global reset. I think it is just like creating a new BIE, seems like more work for little reason.

**Comment by asdimitriadis** [comment]
The reset button should load all initial values to the BIE node from the corresponding CC.
Now, it gets the values from the previous update which is not correct.

**Comment by hakjuoh** [comment]
@asdimitriadis Just made a commit. I have only one problem that the cardinality max does not reset.
Let me know if you found other issues.

**Comment by asdimitriadis** [comment]
@hakjuoh could you please check the following?

1. Open a BIE
2. Make some changes to a BIE node
3. Update the BIE
4. Reopen the BIE
5. Visit the BIE node of the Step 2

At this point there are the following issues:
1. If I click the BIE detail reset button there is no confirmation box in order to confirm my intention to reset the BIE node detail.
2. If I click the BIE detail reset button the values of the node do not go back to their init ones. The expected behavior is that when we click BIE detail reset button the values of the node should go back to the ones related to the CC.

**Comment by rekuku** [comment]
Oh, it's different from what I implemented.
I implemented reset values to previously saved data.
But @kbserm and @asdimitriadis 's intentions are reset values to CC's data.

Can you confirm this?

**Comment by asdimitriadis** [comment]
I confirm this intention. The detail reset button should reset the values to CC's data and not to previously saved data.

I believe it is also good to have a confirmation dialog before resetting the values. When the user clicks the detail reset button, a dialog appears where the user has to confirm his intention of resetting the values of the BIE node.

Note that we do not need the BIE reset button anymore (It is already removed).

**Comment by rekuku** [comment]
@asdimitriadis Now it resets to CC's initial values with confirming dialog.
Please check this.
![Screen Shot 2021-08-31 at 9 48 56 PM](https://user-images.githubusercontent.com/10194354/131598601-f6ca1ddd-e840-4cf5-9ac7-dc7e30396c63.png)

**Comment by asdimitriadis** [comment]
It works well.
