### ISSUE TITLE
Enable SSO

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#728]

**Comment by michaelfigura** [comment]
1. Determine Identity Service intended to be used by LM. Land 'O Lakes uses Ping, integrated with AD.
2. Sequence diagram for modifications required in Score code base
3. Research open-source libraries to implement
4. Migration road map
5. Timeline proposed for implementation

**Comment by hakjuoh** [comment]
```
The preferred architecture for microservices authentication 
and coarse-grained access control is to make use of OAUTH / OpenID Connect 
and PingFederate (from the Federation Services team). 

That way we can integrate with Active Directory but via open standards 
that lend themselves well to microservices development.
```

**Comment by hakjuoh** [comment]
> 4. Migration road map

@kbserm Here's a road map to integrate OpenID connect identity providers (IdPs).

* We made an assumption that every account from IdPs has an end-user role.
1. Put configurable properties such as `idp_name`, `idp_url`, etc., on Score web for adding IdPs.
2. Add `app_idp_user` tables on Score repo to distinguish between existing users and IdP users.
3. Disable user management function to modify IdP users.
4. Develop/Test a function using public IdPs such as Google and Facebook.
5. Provide a snippet or a document of the way to integrate PingFederate access to @michaelfigura.

**Comment by smorgan19** [comment]
Summary of questions regarding existing accounts.

How does your modifications effect existing user accounts that are not in the ping system.  An example is the OAGI account, which wouldn’t be in the ping system, but my employee username would be in ping.  The next question is what happens to the existing accounts, so initially most accounts were registered with the users respective username/employee id, will the changes reflect as a new user or existing or cause a conflict?

Serm's Solution:
A Score admin log into Score. On the account management page, he/she has a choice to create a Score (end user) account based on Ping. He will just put in the Ping user id. The next time the actual user can log on with that user id and choose log in via Ping.

Follow up Questions:
Users will have the ability to use both the standard login method and SSO, but the SSO option has to be enable by an admin on an account by account basis.  So say for instance in the case where an score account like OagiDev which doesn’t have a Ping account would be able to use the standard login, but not the SSO since it’s not in the Ping system.  While another which has a score username of score123 and score password and also has a username of score123 in the Ping system with a different or same password as the score account password can use either the SSO option or standard score login without being considered two different users within the system once the admin goes and selects the SSO option.  

I am trying gauge how this will affect the existing data within score, so in the case of the score123 which already exists in score and has BIE or Code Lists that are published or being edited, switching to the SSO option wouldn’t make them a new user.  Those items would still be connected to the account.  This also raises questions about account creation with SSO as well.  I am assuming this method would still require an admin to create a new user within the score system.  The admin would use Ping system username as the initial username and select the SSO option, and give the user some temp password as a backup, until the chose the SSO login.  Or would the Score tool recognize the user doesn’t exist in the system and create the account based on the SSO information provided in the JWT token.

**Comment by kbserm** [comment]
@smorgan19 First, let me say that the assumption is LM would only want selective users to be accessible to Score. So we don't make a self-sign-up functionality.

As for the existing user accounts, the Score admin should be able to turn an existing account into a Ping account. The user ID would match the Ping account.

**Comment by smorgan19** [comment]
@kbserm what is going to happen to the non-sso accounts?  Are they going to be able to change their username to match the SSO username within score?  For those that do not want to change their username or use score since they have a non-sso account username, I am assuming would still be able to use the standard login.

**Comment by kbserm** [comment]
@smorgan19 yes, username update should be allowed, so that any account including existing, non-sso account can be updated.

**Comment by smorgan19** [comment]
Hi @kbserm do you all have a timeline of when we can expect this release to be done.

**Comment by kbserm** [comment]
We should have it for deployment testing by end of Aug.
