### ISSUE TITLE
Error in state filtering on View CC page

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#749]
when I selected all the states, no CC is listed.

**Comment by rekuku** [comment]
@kbserm 
Currently Editing, Candidate, Publishing, and Deprecated are inquired by single UI component.
But "Editing, Candidate, Publishing" and "Deprecated" are different data.

If user select all of Editing, Candidate, Publishing, and Deprecated, than it means STATUS IN (Editing, Candidate, Publishing) AND is_deprecated = 1,
However, since such data does not exist in the data, so no results are queried.

If this behavior is not natural, we can separate the Status and Is_deprecated queries from the UI.

**Comment by kbserm** [comment]
@rekuku I think it makes sense the separate Status and Deprecated filter.

**Comment by kbserm** [comment]
Or can you simply change the where condition to  STATUS IN (Editing, Candidate, Publishing) OR is_deprecated = 1 ? Would this cause problem?

**Comment by rekuku** [comment]
We can change AND to OR, but it would be better to separate that UI. Because if we use OR, we should use the AND operator when Deprecated = 0 ( STATUS IN (Editing) OR is_deprecated = 0 will be showing almost every CCs  ), and only use the OR operator when Deprecated = 1, which might be more confusing.

**Comment by rekuku** [comment]
<img width="1045" alt="Screen Shot 2020-01-10 at 11 02 00 AM" src="https://user-images.githubusercontent.com/10194354/72167341-f6fc5900-3398-11ea-98ea-36d82b448f50.png">

Add `Deprecated` checkbox to Cc List search form.
So now user can recognize `Deprecated` as separate data.

@asdimitriadis Please review and test this.

**Comment by asdimitriadis** [comment]
It works good.

**Comment by hakjuoh** [comment]
@asdimitriadis I changed the UI component for "Deprecated" filter from 'mat-checkbox' to 'mat-select' to keep consistency.

<img width="244" alt="Screen Shot 2020-01-30 at 12 41 11 PM" src="https://user-images.githubusercontent.com/16102116/73475166-d141ee80-435d-11ea-9740-250f426567e5.png">
