### ISSUE TITLE
The primitive type cannot be updated once is changed

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#762]
The issue is that we cannot set back the primitive type to Primitive once we updated it for instance to "Agency".

**Comment by hakjuoh** [comment]
@asdimitriadis @rekuku This issue happened that the values of multiple primitive types allowed to store into DB although only one of those must be existed.

<img width="782" alt="Screen Shot 2020-02-05 at 1 12 27 PM" src="https://user-images.githubusercontent.com/16102116/73871761-6c363f00-481c-11ea-91c6-c776884e215c.png">

I fixed it, and in order to support backward compatibility, I put the following logic as same as JSF.

1. If 'agency' has a value, 'bdt / dt_sc' and 'code' will be ignored (i.e. set to null).
2. If 'code' has a value, 'bdt / dt_sc' and 'agency' will be ignored (i.e. set to null).
3. Otherwise, 'code' and 'agency' will be ignored (i.e. set to null).

**Comment by asdimitriadis** [comment]
Tested. It works now.

**Comment by kbserm** [comment]
@hakjuoh I am wondering what you mean by 'for backward compatibility'?

**Comment by hakjuoh** [comment]
> @hakjuoh I am wondering what you mean by 'for backward compatibility'?

I’m worried a situation that some users have already updated to 1.3.0 and these wrong data generated in their DB. This bug fix could handle with wrong data.
