### ISSUE TITLE
Bring back Lucene ranked score sort for Searching

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#775]
I tried to demonstrate creating a new a BIE for Location yesterday, and in the old version with Lucene, Location component would be first in the list.  I simply could not find it without this sorting approach -- there were 97 pages, and it was somewhere in that list.

Bring Back Lucene -- great title for a new song!!

**Comment by kbserm** [comment]
@dubnemo In a few days we will release a version which you can do exact search. To create BIE for Location; you should enter in double quote "Location. " or "Location. Location".

Lucene has something we couldn't quite understand yet like searching with bom vs. BOM returned different results.

**Comment by dubnemo** [comment]
@kbserm I think that should work.

**Comment by michaelfigura** [comment]
This is bugging the heck out of me. Why is the search "Purchase Order. Purchase Order" showing up on page 3 of the results? I waste countless time each day sifting through search results. @kbserm

**Comment by kbserm** [comment]
@michaelfigura because search result is sorted by last modification date by default. Click the DEN column to have it sorted by DEN.  The browser remembers your sorting choice to some extent. Sorting by matching score based on Lucene might be better, but we still have other priorities. Anyway, I will ask Dimitrije to look into Lucene integration.
