### ISSUE TITLE
Deleting and restoring ACC functionality

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#805]

**Comment by asdimitriadis** [comment]
The issue is that if a developer restores an ACC that has some associations (e.g., an ASCCP and a BCCP) the associations are not restored.

The expected behavior is that the developer can open an ACC and restore it. One he does this, then all of its associations shall be restored as well.

**Comment by asdimitriadis** [comment]
The issue is that if a developer opens an ASCCP that uses a deleted ACC there is no flag indicating that the ASCCP is in invalid state.
To reproduce it:
1. Create the ACCw
2. Create the ASCCPw and choose the ACCw.
3. Open the ACCw and delete it.
4. Open the ASCCPw.
There is no flag highlighting that the ASCCP is in invalid state (there is only the flag indicating that the ACCw is deleted).

The expected behavior is that upon opening an ASCCP that uses a deleted ACC, the ASCCP shall be highlighted or flagged indicating that the ASCCP is an invalid state. The system shall provide an option for the developer to choose another ACC. The system shall also allow the developer to open the deleted ACC in another tab where he can restore it. The developer may need to refresh the ASCCP detail page to clear the invalid flag.

**Comment by kbserm** [comment]
ACC already published but still has a Delete menu item.

![image](https://user-images.githubusercontent.com/7863166/89427585-622cc480-d709-11ea-9231-ef6d12e31d47.png)

**Comment by asdimitriadis** [comment]
Note that  "The system shall provide an option for the developer to choose another ACC." of my previous comment is fixed. We can change the ACC of an ASCCP.
Also note that the "The system shall also allow the developer to open the deleted ACC in another tab where he can restore it. The developer may need to refresh the ASCCP detail page to clear the invalid flag." is fixed.

So we have to fix this: "The issue is that if a developer opens an ASCCP that uses a deleted ACC there is no flag indicating that the ASCCP is in invalid state."
