### ISSUE TITLE
v1.3.1.2 Extensions not showing up, enabled extensions unchecked

### ISSUE THREAD

**Issue by dubnemo** [OAGi/Score#823]
in BioPharma site, catalog.catalogLine.item.packaging.extension items are not showing up, even though they are expressed in the JSON Schema.

![image](https://user-images.githubusercontent.com/32434235/81849053-94b88e00-951b-11ea-939e-6a9250e98df5.png)

[Catalog-oagis-id-ee565b7daa7e47569145abd4648f223c.zip](https://github.com/OAGi/Score/files/4624149/Catalog-oagis-id-ee565b7daa7e47569145abd4648f223c.zip)

**Comment by dubnemo** [comment]
Is there an existing Issue for this?

**Comment by dubnemo** [comment]
select * from bbie where bbie_id in (13732, 17101);

delete from bbie where bbie_id=17101;

select * from bcc where bcc_id in (4155,138);

**Comment by dubnemo** [comment]
@hakjuoh @kbserm Have you had any time to review the biopharm DB to understand the why this may be happening?  If there are duplicates.   Yesterday, while I was on PTO, one of the projects encountered the same issue on a copied BIE.   The JournalEntry did not show the extension for Distribution, and it kept getting serialized when expressing to JSON Schema or OpenAPI Spec template.

**Comment by hakjuoh** [comment]
@asdimitriadis Here's how you can reproduce this issue from scratch.

1. Create [Catalog. Catalog] BIE
2. Expand the tree to go to [Catalog > Catalog Line > Item > Package > Extension] and create UEG.
3. Append [Effective Date Time] and [GTINID] BCCPs and make it 'Published'.
<img width="242" alt="Screen Shot 2020-05-20 at 3 53 08 PM" src="https://user-images.githubusercontent.com/16102116/82491704-fe541180-9ab2-11ea-9d60-13d2de74c935.png">
4. Go back to the BIE and expand the tree. You now can see additional two BBIEPs in UEG. Check `used` for those as follows,
<img width="276" alt="Screen Shot 2020-05-20 at 3 54 06 PM" src="https://user-images.githubusercontent.com/16102116/82491802-293e6580-9ab3-11ea-85b6-4bbbe1f8d6cd.png">
5. Revise the UEG, append [Manufacturing Item Instance] ASCCP, and make it 'Published' again.
<img width="238" alt="Screen Shot 2020-05-20 at 3 54 38 PM" src="https://user-images.githubusercontent.com/16102116/82491900-5559e680-9ab3-11ea-813e-3f15c0e4ba11.png">
6. Go back to the BIE and expand the tree again. At this moment, it looks like you lost two BBIEPs' information you've made before at step 4 such as `used` although you can see two BBIEP and one ASBIEP as same as UEG has.
<img width="261" alt="Screen Shot 2020-05-20 at 3 55 36 PM" src="https://user-images.githubusercontent.com/16102116/82492027-8afecf80-9ab3-11ea-8567-5cc64601d3e3.png">

It caused by not updating existing ASBIE and BBIE references after revising the UEG. All BIEs should indicate to the latest records whose `release_id` value is NOT NULL. After revising the UEG, however, existing ASCC/BCC records also stack the table up as histories and its ASCC/BCC ID also get changed. Here's an example of how BCC and BBIE tables look after revising the UEG.

| BCC ID | DEN | Revision |
| ---------------- | --- | --------- |
| 1 | Packaging User Extension Group. Effective Date Time. Date Time | 1 |
| 2 | Packaging User Extension Group. GTINID. Identifier | 1 |
| 3 | Packaging User Extension Group. Effective Date Time. Date Time | 2 |
| 4 | Packaging User Extension Group. GTINID. Identifier | 2 |

| BBIE ID | BASED BCC ID | used |
| ------- | --------------- | ---- |
| 1 | 1 | true |
| 2 | 2 | true |

When the user expands the extension in BIE tree, there are no BIE records following the latest BIE records (in this example, BCC ID 3 and 4). So it creates new BBIEs with default values as follows,

| BBIE ID | BASED BCC ID | used |
| ------- | --------------- | ---- |
| 3 | 3 | false |
| 4 | 4 | false |

and that's the reason it looked like existing info were missing.

I put a guarding logic on the extension state transition, particularly 'Published' that all based references of ASBIEs and BBIEs (i.e., `based_ascc_id` and `based_bcc_id`) update to the latest ones.

Let me know if you need anything else to test and validate this issue.

**Comment by kbserm** [comment]
@hakjuoh thanks for the detailed documentation. On Tues let's discuss about on Tue. I am wondering, with the 2.0 release, this issue might be simpler or
more complicated. Although end user CCs won't have history records, developer CC's they use do have history records.

**Comment by asdimitriadis** [comment]
Tested and it works.
