### ISSUE TITLE
Extension component

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#886]
The developer cannot directly create Extension component type.

There is a macro to create extension element for an ACC. As only local Extension element is used. The macro shouldn't generate the unused global element with qualified name such as WorderHeaderExtension. 

There is an idea about offering remove macro as well. This may be good if the ACC name changes. Perhaps a macro to Sync Extension is better. Release validation should still check the extension naming pattern. 

If the core component is deleted, offer to delete related extension as well. If core component is stored, offer to restore the extension as well. This is better but can be implemented in 2.x.

**Comment by rekuku** [comment]
Implemented: 
	Generate Extension Components (ACC, ASCCP)
	Sync Name and namespaceId between parent ACC and Extensions.
	Block editing extension component’s properties, except definition and definitionSource.
	If user `Remove` extension ASCC from parent ACC, then generated Extensions also `Removed` from database.

To be implemented:
	Sync the `State` between parent ACC and Extension.
	Naming Validation In Release management.

If possible, I'd like to `Remove` the generated Extension components instead of `Delete`. 
Because the generated Extension component will not be used by other CCs.
Can we handle it like this? @kbserm

**Comment by hakjuoh** [comment]
@rekuku Note that this is going to adopt to creating BOD/Verb component either.

**Comment by kbserm** [comment]
@rekuku It looks like the system keeps creating duplicate Extension ASCCP and ACC, if I removed the extension from the ACC and then hit Create OAGi Extension again. 

I believe this didn't happen earlier.

**Comment by hakjuoh** [comment]
This extension macro now works along with Extension ASCCP and its associated ACC for updating object class term, namespace, and states. Note that there is a case that can potentially cause the duplicating problem.

1. Create ACC with 'Test 1' object class term
2. Click 'Create Extension ASCCP'
3. Delete Extension ASCCP or Remove Extension ASCC
4. Change the object class term with 'Test 2'
5. Click 'Create Extension ASCCP'

There is no way to find a previous extension ASCCP using the object class term because it's changed after deleting.

**Comment by kbserm** [comment]
"There is no way to find a previous extension ASCCP using the object class term because it's changed after deleting." That's what is expected, so it is ok.

**Comment by kbserm** [comment]
We changed back to previous @rekuku commit because @hakjuoh commit tried to tightly couple the ACC and the extension components. It worked well but unfortunately there is another hole/error when there are extension CCs with the same names. Although @rekuku commit produces duplicate extension components, we will live with that for now. I will put another enhancement issue in future release to see if we could do better.

**Comment by kbserm** [comment]
@asdimitriadis I put this in the future test script card. Please try to add a test script that include the create, removal, and recreate extension.

**Comment by asdimitriadis** [comment]
There is an related to the fact that we can create an Extension even if the component type of the ACC is different than "Semantics" e.g. Base or Semantics group.

To reproduce the issue:
1. Create an ACC
2. Sets its type to be "Base (Abstract)"
3. Invoke the "Create OAGi extension component".

A extension is successfully created. 

The expected behavior is that the macro can be invoked only if the component type is semantics.

**Comment by hakjuoh** [comment]
@asdimitriadis The problem is that the user can make it to ‘Base’ type after creating the extension component. In my opinion, the assertion may be

`The component type must be “Semantic” and cannot be changed if it has ‘Extension’.`

**Comment by kbserm** [comment]
I think do not offer the menu when it is base component type is enough. Defer the rest to validation, I. e., we will catch it during that time if the use happen to change from semantic to base.

**Comment by kbserm** [comment]
The reason is I think too many client side UI rules can make the software brittle and tend to be buggy.
