### ISSUE TITLE
Add view/edit code list under BIE as well.

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#949]
It would be good to default to the latest release branch when open this page under the BIE menu.

**Comment by hakjuoh** [comment]
Now the branch selection dropbox has sorted elements by the following logic:

1. Sorted by ID with descending order.
2. If the user has a developer role, 'Working' branch would be on the front. Otherwise, 'Working' branch would be on the rear.

<img width="257" alt="Screen Shot 2020-10-08 at 9 25 58 AM" src="https://user-images.githubusercontent.com/16102116/95464732-4b446180-0948-11eb-918c-95774bf32be8.png">
[For developers]

<img width="261" alt="Screen Shot 2020-10-08 at 9 25 45 AM" src="https://user-images.githubusercontent.com/16102116/95464740-4da6bb80-0948-11eb-89f4-76efa75f8102.png">
[For end-users]

**Comment by hakjuoh** [comment]
@kbserm 
<img width="207" alt="Screen Shot 2020-10-09 at 4 28 05 PM" src="https://user-images.githubusercontent.com/16102116/95628620-6d270c80-0a4c-11eb-9ad1-bc887dc479fb.png">
