### ISSUE TITLE
Issue of the components of a BIE that are required by default

### ISSUE THREAD

**Issue by asdimitriadis** [OAGi/Score#953]
The issue is related to the nodes of a BIE that has Min and Max Cardinality equal to 1.
Those components are disabled but are required by default.

Please see the tooltip below.

![reruired](https://user-images.githubusercontent.com/37205288/95486644-4213be80-0961-11eb-9ef6-583406d75ea0.png)

**Comment by hakjuoh** [comment]
@asdimitriadis @kbserm 'Required' components now cannot get checked by users. Note that even the required BIEs are checked, it still may not be in DB until the user clicks 'Update' button. Because BIEs never automatically created in this release.

<img width="616" alt="Screen Shot 2020-10-08 at 1 30 21 PM" src="https://user-images.githubusercontent.com/16102116/95493449-8061ab80-096a-11eb-89af-a5ed3e9dfebc.png">

**Comment by asdimitriadis** [comment]
It works good.
