### ISSUE TITLE
Deriving code list in end user does not behave like in 1.x

### ISSUE THREAD

**Issue by kbserm** [OAGi/Score#983]
see TC 17.4 about derivation.

**Comment by kbserm** [comment]
@hakjuoh while amending end user code list with derived values, the end user shouldn't be able to change the Used flag of existing derived values whose Used flag is true anymore.

**Comment by hakjuoh** [comment]
> @hakjuoh while amending end user code list with derived values, the end user shouldn't be able to change the Used flag of existing derived values whose Used flag is true anymore.

Now the 'Used' flag can be enabled only if the derived value was unchecked in the previous revision.

[ Enabled 'Used' checkbox because it was unused in the previous revision. ]
<img width="526" alt="Screen Shot 2020-10-14 at 12 01 14 PM" src="https://user-images.githubusercontent.com/16102116/96014958-fa83ab80-0e14-11eb-8a30-05e41084b136.png">

[ Disabled 'Used' checkbox because it was used in the previous revision. ]
<img width="609" alt="Screen Shot 2020-10-14 at 11 59 53 AM" src="https://user-images.githubusercontent.com/16102116/96014825-d1fbb180-0e14-11eb-88c8-45918dcc1400.png">

**Comment by asdimitriadis** [comment]
Seems to work good. Tried manually.
